In [1]:
import numpy as np

In [2]:
N = 8

In [3]:
board_state_memory = {}

In [4]:
board = np.zeros((N, N), np.int8)

In [5]:
def create_board_string(board):
    board_string = ''
    for i in range(N):
        for j in range(N):
            board_string += str(board[i][j])
            
    return board_string

In [6]:
create_board_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [23]:
def is_board_safe(board):
    
    board_key = create_board_string(board)
    
    if board_key in board_state_memory:
        #print('Using cached information')
        return board_state_memory[board_key]
    
    row_sum = np.sum(board, axis=1)
    if len(row_sum[np.where(row_sum > 1)]) > 0:
        board_state_memory[board_key] = False
        return False
    
    col_sum = np.sum(board, axis=0)
    if len(col_sum[np.where(col_sum > 1)]) > 0:
        board_state_memory[board_key] = False
        return False
    
    diags = [board[::-1, :].diagonal(i) for i in range(-board.shape[0] + 1, board.shape[1])]
    
    diags.extend(board.diagonal(i) for i in range(board.shape[1] - 1, -board.shape[0], -1))
    
    for diag in diags:
        if np.sum(diag) > 1:
            board_state_memory[board_key] = False
            return False
        
    board_state_memory[board_key] = True
    
    return True

In [24]:
board_copy = board.copy()

In [25]:
board_copy[0][0] = 1
board_copy[0][3] = 1

In [26]:
print(board_copy)
is_board_safe(board_copy)

[[1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]


False

In [27]:
board_copy = board.copy()

In [28]:
board_copy[1][0] = 1
board_copy[2][0] = 1

In [29]:
print(board_copy)
is_board_safe(board_copy)

[[1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0]
 [1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]


False

In [30]:
board_copy[1][0] = 1
board_copy[2][3] = 1
board_copy[0][1] = 1

In [31]:
print(board_copy)
is_board_safe(board_copy)

[[1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0]
 [1 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]


False

In [32]:
def place_queen(board, column):
    if column >= N:
        return True
    
    for row in range(N):
        board[row][column] = 1
        
        safe = False
        if is_board_safe(board):
            safe = place_queen(board, column + 1)
            
        if not safe:
            board[row][column] = 0
        else:
            break
            
    return safe

In [35]:
#board_state_memory

In [36]:
board = np.zeros((N, N), np.int8)
placed = place_queen(board, 0)
print(placed)

True


In [37]:
board

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=int8)

In [38]:
#board_state_memory

In [39]:
board = np.zeros((N, N), np.int8)
placed = place_queen(board, 0)
#print(placed)

In [40]:
board

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=int8)